# 元素周期表和映射只初始化一次，避免每次请求构造
_symbol_map = None


def periodic_map() -> dict:
    global _symbol_map
    if _symbol_map is not None:
        return _symbol_map
    _periodic_table = {
        "H": {"name": "Hydrogen", "chinese_name": "氢", "atomic_number": 1, "atomic_weight": 1.008},
        "He": {"name": "Helium", "chinese_name": "氦", "atomic_number": 2, "atomic_weight": 4.0026},
        "Li": {"name": "Lithium", "chinese_name": "锂", "atomic_number": 3, "atomic_weight": 6.94},
        "Be": {"name": "Beryllium", "chinese_name": "铍", "atomic_number": 4, "atomic_weight": 9.0122},
        "B": {"name": "Boron", "chinese_name": "硼", "atomic_number": 5, "atomic_weight": 10.81},
        "C": {"name": "Carbon", "chinese_name": "碳", "atomic_number": 6, "atomic_weight": 12.011},
        "N": {"name": "Nitrogen", "chinese_name": "氮", "atomic_number": 7, "atomic_weight": 14.007},
        "O": {"name": "Oxygen", "chinese_name": "氧", "atomic_number": 8, "atomic_weight": 15.999},
        "F": {"name": "Fluorine", "chinese_name": "氟", "atomic_number": 9, "atomic_weight": 18.998},
        "Ne": {"name": "Neon", "chinese_name": "氖", "atomic_number": 10, "atomic_weight": 20.180},
        "Na": {"name": "Sodium", "chinese_name": "钠", "atomic_number": 11, "atomic_weight": 22.990},
        "Mg": {"name": "Magnesium", "chinese_name": "镁", "atomic_number": 12, "atomic_weight": 24.305},
        "Al": {"name": "Aluminum", "chinese_name": "铝", "atomic_number": 13, "atomic_weight": 26.982},
        "Si": {"name": "Silicon", "chinese_name": "硅", "atomic_number": 14, "atomic_weight": 28.085},
        "P": {"name": "Phosphorus", "chinese_name": "磷", "atomic_number": 15, "atomic_weight": 30.974},
        "S": {"name": "Sulfur", "chinese_name": "硫", "atomic_number": 16, "atomic_weight": 32.06},
        "Cl": {"name": "Chlorine", "chinese_name": "氯", "atomic_number": 17, "atomic_weight": 35.45},
        "Ar": {"name": "Argon", "chinese_name": "氩", "atomic_number": 18, "atomic_weight": 39.948},
        "K": {"name": "Potassium", "chinese_name": "钾", "atomic_number": 19, "atomic_weight": 39.098},
        "Ca": {"name": "Calcium", "chinese_name": "钙", "atomic_number": 20, "atomic_weight": 40.078},
        "Sc": {"name": "Scandium", "chinese_name": "钪", "atomic_number": 21, "atomic_weight": 44.956},
        "Ti": {"name": "Titanium", "chinese_name": "钛", "atomic_number": 22, "atomic_weight": 47.867},
        "V": {"name": "Vanadium", "chinese_name": "钒", "atomic_number": 23, "atomic_weight": 50.942},
        "Cr": {"name": "Chromium", "chinese_name": "铬", "atomic_number": 24, "atomic_weight": 51.996},
        "Mn": {"name": "Manganese", "chinese_name": "锰", "atomic_number": 25, "atomic_weight": 54.938},
        "Fe": {"name": "Iron", "chinese_name": "铁", "atomic_number": 26, "atomic_weight": 55.845},
        "Co": {"name": "Cobalt", "chinese_name": "钴", "atomic_number": 27, "atomic_weight": 58.933},
        "Ni": {"name": "Nickel", "chinese_name": "镍", "atomic_number": 28, "atomic_weight": 58.693},
        "Cu": {"name": "Copper", "chinese_name": "铜", "atomic_number": 29, "atomic_weight": 63.546},
        "Zn": {"name": "Zinc", "chinese_name": "锌", "atomic_number": 30, "atomic_weight": 65.38},
        "Ga": {"name": "Gallium", "chinese_name": "镓", "atomic_number": 31, "atomic_weight": 69.723},
        "Ge": {"name": "Germanium", "chinese_name": "锗", "atomic_number": 32, "atomic_weight": 72.630},
        "As": {"name": "Arsenic", "chinese_name": "砷", "atomic_number": 33, "atomic_weight": 74.922},
        "Se": {"name": "Selenium", "chinese_name": "硒", "atomic_number": 34, "atomic_weight": 78.971},
        "Br": {"name": "Bromine", "chinese_name": "溴", "atomic_number": 35, "atomic_weight": 79.904},
        "Kr": {"name": "Krypton", "chinese_name": "氪", "atomic_number": 36, "atomic_weight": 83.798},
        "Rb": {"name": "Rubidium", "chinese_name": "铷", "atomic_number": 37, "atomic_weight": 85.468},
        "Sr": {"name": "Strontium", "chinese_name": "锶", "atomic_number": 38, "atomic_weight": 87.62},
        "Y": {"name": "Yttrium", "chinese_name": "钇", "atomic_number": 39, "atomic_weight": 88.906},
        "Zr": {"name": "Zirconium", "chinese_name": "锆", "atomic_number": 40, "atomic_weight": 91.224},
        "Nb": {"name": "Niobium", "chinese_name": "铌", "atomic_number": 41, "atomic_weight": 92.906},
        "Mo": {"name": "Molybdenum", "chinese_name": "钼", "atomic_number": 42, "atomic_weight": 95.95},
        "Tc": {"name": "Technetium", "chinese_name": "锝", "atomic_number": 43, "atomic_weight": 98},
        "Ru": {"name": "Ruthenium", "chinese_name": "钌", "atomic_number": 44, "atomic_weight": 101.07},
        "Rh": {"name": "Rhodium", "chinese_name": "铑", "atomic_number": 45, "atomic_weight": 102.91},
        "Pd": {"name": "Palladium", "chinese_name": "钯", "atomic_number": 46, "atomic_weight": 106.42},
        "Ag": {"name": "Silver", "chinese_name": "银", "atomic_number": 47, "atomic_weight": 107.87},
        "Cd": {"name": "Cadmium", "chinese_name": "镉", "atomic_number": 48, "atomic_weight": 112.41},
        "In": {"name": "Indium", "chinese_name": "铟", "atomic_number": 49, "atomic_weight": 114.82},
        "Sn": {"name": "Tin", "chinese_name": "锡", "atomic_number": 50, "atomic_weight": 118.71},
        "Sb": {"name": "Antimony", "chinese_name": "锑", "atomic_number": 51, "atomic_weight": 121.76},
        "Te": {"name": "Tellurium", "chinese_name": "碲", "atomic_number": 52, "atomic_weight": 127.60},
        "I": {"name": "Iodine", "chinese_name": "碘", "atomic_number": 53, "atomic_weight": 126.90},
        "Xe": {"name": "Xenon", "chinese_name": "氙", "atomic_number": 54, "atomic_weight": 131.29},
        "Cs": {"name": "Cesium", "chinese_name": "铯", "atomic_number": 55, "atomic_weight": 132.91},
        "Ba": {"name": "Barium", "chinese_name": "钡", "atomic_number": 56, "atomic_weight": 137.33},
        "La": {"name": "Lanthanum", "chinese_name": "镧", "atomic_number": 57, "atomic_weight": 138.91},
        "Ce": {"name": "Cerium", "chinese_name": "铈", "atomic_number": 58, "atomic_weight": 140.12},
        "Pr": {"name": "Praseodymium", "chinese_name": "镨", "atomic_number": 59, "atomic_weight": 140.91},
        "Nd": {"name": "Neodymium", "chinese_name": "钕", "atomic_number": 60, "atomic_weight": 144.24},
        "Pm": {"name": "Promethium", "chinese_name": "钷", "atomic_number": 61, "atomic_weight": 145},
        "Sm": {"name": "Samarium", "chinese_name": "钐", "atomic_number": 62, "atomic_weight": 150.36},
        "Eu": {"name": "Europium", "chinese_name": "铕", "atomic_number": 63, "atomic_weight": 151.96},
        "Gd": {"name": "Gadolinium", "chinese_name": "钆", "atomic_number": 64, "atomic_weight": 157.25},
        "Tb": {"name": "Terbium", "chinese_name": "铽", "atomic_number": 65, "atomic_weight": 158.93},
        "Dy": {"name": "Dysprosium", "chinese_name": "镝", "atomic_number": 66, "atomic_weight": 162.50},
        "Ho": {"name": "Holmium", "chinese_name": "钬", "atomic_number": 67, "atomic_weight": 164.93},
        "Er": {"name": "Erbium", "chinese_name": "铒", "atomic_number": 68, "atomic_weight": 167.26},
        "Tm": {"name": "Thulium", "chinese_name": "铥", "atomic_number": 69, "atomic_weight": 168.93},
        "Yb": {"name": "Ytterbium", "chinese_name": "镱", "atomic_number": 70, "atomic_weight": 173.05},
        "Lu": {"name": "Lutetium", "chinese_name": "镥", "atomic_number": 71, "atomic_weight": 174.97},
        "Hf": {"name": "Hafnium", "chinese_name": "铪", "atomic_number": 72, "atomic_weight": 178.49},
        "Ta": {"name": "Tantalum", "chinese_name": "钽", "atomic_number": 73, "atomic_weight": 180.95},
        "W": {"name": "Tungsten", "chinese_name": "钨", "atomic_number": 74, "atomic_weight": 183.84},
        "Re": {"name": "Rhenium", "chinese_name": "铼", "atomic_number": 75, "atomic_weight": 186.21},
        "Os": {"name": "Osmium", "chinese_name": "锇", "atomic_number": 76, "atomic_weight": 190.23},
        "Ir": {"name": "Iridium", "chinese_name": "铱", "atomic_number": 77, "atomic_weight": 192.22},
        "Pt": {"name": "Platinum", "chinese_name": "铂", "atomic_number": 78, "atomic_weight": 195.08},
        "Au": {"name": "Gold", "chinese_name": "金", "atomic_number": 79, "atomic_weight": 196.97},
        "Hg": {"name": "Mercury", "chinese_name": "汞", "atomic_number": 80, "atomic_weight": 200.59},
        "Tl": {"name": "Thallium", "chinese_name": "铊", "atomic_number": 81, "atomic_weight": 204.38},
        "Pb": {"name": "Lead", "chinese_name": "铅", "atomic_number": 82, "atomic_weight": 207.2},
        "Bi": {"name": "Bismuth", "chinese_name": "铋", "atomic_number": 83, "atomic_weight": 208.98},
        "Po": {"name": "Polonium", "chinese_name": "钋", "atomic_number": 84, "atomic_weight": 209},
        "At": {"name": "Astatine", "chinese_name": "砹", "atomic_number": 85, "atomic_weight": 210},
        "Rn": {"name": "Radon", "chinese_name": "氡", "atomic_number": 86, "atomic_weight": 222},
        "Fr": {"name": "Francium", "chinese_name": "钫", "atomic_number": 87, "atomic_weight": 223},
        "Ra": {"name": "Radium", "chinese_name": "镭", "atomic_number": 88, "atomic_weight": 226},
        "Ac": {"name": "Actinium", "chinese_name": "锕", "atomic_number": 89, "atomic_weight": 227},
        "Th": {"name": "Thorium", "chinese_name": "钍", "atomic_number": 90, "atomic_weight": 232.04},
        "Pa": {"name": "Protactinium", "chinese_name": "镤", "atomic_number": 91, "atomic_weight": 231.04},
        "U": {"name": "Uranium", "chinese_name": "铀", "atomic_number": 92, "atomic_weight": 238.03},
        "Np": {"name": "Neptunium", "chinese_name": "镎", "atomic_number": 93, "atomic_weight": 237},
        "Pu": {"name": "Plutonium", "chinese_name": "钚", "atomic_number": 94, "atomic_weight": 244},
        "Am": {"name": "Americium", "chinese_name": "镅", "atomic_number": 95, "atomic_weight": 243},
        "Cm": {"name": "Curium", "chinese_name": "锔", "atomic_number": 96, "atomic_weight": 247},
        "Bk": {"name": "Berkelium", "chinese_name": "锫", "atomic_number": 97, "atomic_weight": 247},
        "Cf": {"name": "Californium", "chinese_name": "锎", "atomic_number": 98, "atomic_weight": 251},
        "Es": {"name": "Einsteinium", "chinese_name": "锿", "atomic_number": 99, "atomic_weight": 252},
        "Fm": {"name": "Fermium", "chinese_name": "镄", "atomic_number": 100, "atomic_weight": 257},
        "Md": {"name": "Mendelevium", "chinese_name": "钔", "atomic_number": 101, "atomic_weight": 258},
        "No": {"name": "Nobelium", "chinese_name": "锘", "atomic_number": 102, "atomic_weight": 259},
        "Lr": {"name": "Lawrencium", "chinese_name": "铹", "atomic_number": 103, "atomic_weight": 266},
        "Rf": {"name": "Rutherfordium", "chinese_name": "𬬻", "atomic_number": 104, "atomic_weight": 267},
        "Db": {"name": "Dubnium", "chinese_name": "𬭊", "atomic_number": 105, "atomic_weight": 270},
        "Sg": {"name": "Seaborgium", "chinese_name": "𬭳", "atomic_number": 106, "atomic_weight": 271},
        "Bh": {"name": "Bohrium", "chinese_name": "𬭛", "atomic_number": 107, "atomic_weight": 270},
        "Hs": {"name": "Hassium", "chinese_name": "𬭶", "atomic_number": 108, "atomic_weight": 277},
        "Mt": {"name": "Meitnerium", "chinese_name": "鿏", "atomic_number": 109, "atomic_weight": 278},
        "Ds": {"name": "Darmstadtium", "chinese_name": "𫟼", "atomic_number": 110, "atomic_weight": 281},
        "Rg": {"name": "Roentgenium", "chinese_name": "𬬭", "atomic_number": 111, "atomic_weight": 282},
        "Cn": {"name": "Copernicium", "chinese_name": "鿔", "atomic_number": 112, "atomic_weight": 285},
        "Fl": {"name": "Flerovium", "chinese_name": "𫓧", "atomic_number": 114, "atomic_weight": 289},
        "Lv": {"name": "Livermorium", "chinese_name": "𫟷", "atomic_number": 116, "atomic_weight": 293},
        "Ts": {"name": "Tennessine", "chinese_name": "鿬", "atomic_number": 117, "atomic_weight": 294},
        "Og": {"name": "Oganesson", "chinese_name": "鿫", "atomic_number": 118, "atomic_weight": 294},
    }
    # Initialize _symbol_map with both element symbols and Chinese names as keys
    _symbol_map = {}
    for symbol, data in _periodic_table.items():
        # Map symbol to element data
        _symbol_map[symbol] = data
        # Map Chinese name to element data
        _symbol_map[data["chinese_name"]] = data

    return _symbol_map
